In [7]:
import numpy as np
# tablice
a = np.array([1,2,3,4,5,6,7])
b = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(np.transpose(b))
c = np.arange(100)
print(c)
d = np.linspace(0, 2, 10)
print(d)
e = np.arange(0, 101, 5)
print(e)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]
[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]


In [35]:
import numpy as np
#liczby losowe
a = np.around(np.random.normal(0, 1, 20), 2)
print(a)
b = np.random.randint(1, 1000, 100)
print(b)
c = np.zeros((3, 2))
print(c)
d = np.ones((3, 2))
print(d)
e = np.random.randint(np.iinfo(np.int32).min, np.iinfo(np.int32).max ,size=(5, 5), dtype=np.int32)
print(e)
#zadania
a = np.random.uniform(0, 10, 10)
b = a.astype(np.int32)
a = np.rint(b).astype(np.int32)
print(a)
print(b)
print(a == b)

[-0.66 -1.32  0.57  0.04 -0.06  0.32  2.12  0.46  0.14  0.07 -1.49  0.25
  0.65 -0.64  1.13  0.04 -1.74 -1.6   1.24  0.58]
[421 440 313 433 676 828 781 305 366 799 631 734 381 634 252 234 292 899
 707 286 663 973 418 508 719 782 947 528 818 524 241 750 181 613  35 396
 207 433  24 601 482 164 551 241 386 892 206 196 134 389 905 866 583 537
 617 514 693 534 956 116 390 840 204  49   3 128 894 308  72  69 750 933
 540 619 812 899 432  86 630 255 464 840 352 367 111 477 959 964 193 752
 179 449 745 613 773 554 432  11 858 283]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[-2127370018 -1956191257  1417429892 -1957276345  1621747145]
 [ 1711214402  1888456972  -401566008   264377898  -920265258]
 [ 1236748093    98698137 -1398984169  1164815052 -1141718632]
 [ -261351459 -1998255830 -1311223278   613453962  -901847887]
 [ 1619006425 -1545897221  1688820464 -1284134435  -169862547]]
[0 5 1 0 6 8 6 3 0 5]
[0 5 1 0 6 8 6 3 0 5]
[ True  True  True  True  True  True  True  True  True

In [45]:
import numpy as np
#selekcja danych
b = np.array([[1,2,3,4,5], [6,7,8,9,10]], dtype = np.int32)
print(np.ndim(b))
print(np.size(b))
print(b[0, 1], b[0, 3])
print(b[0])
print(b[:, 0])
a = np.random.randint(0, 101, (20, 7))
print(a)
print(a[:, :4])

2
10
2 4
[1 2 3 4 5]
[1 6]
[[  3  87  84  50  67  67  29]
 [ 97  27  50  31   2  90  94]
 [ 10   9  44  95  28  74  32]
 [ 86  21  38  20  55  31  94]
 [ 87  66  47  24  63  79  49]
 [ 19  12  13  46  37  41  77]
 [ 32  57  87  88  99  57  11]
 [ 59   2  10 100  24  45  69]
 [ 17  51  40  68  22   0  43]
 [  3  80  27   2  32  89  94]
 [ 47  37  89  52  38  35  70]
 [ 65   7  96  96  85  38  48]
 [ 79  34  97  53  74  21  72]
 [ 93  59  16  13   6  23  24]
 [ 34  16  23  30  91  59  85]
 [ 76  82   6  68  11  81  15]
 [ 58  48  17  31  91  96  84]
 [  3  73   2  57  86  79  71]
 [ 40   0 100  82  31  45  43]
 [ 92   3  52  11  79  69  99]]
[[  3  87  84  50]
 [ 97  27  50  31]
 [ 10   9  44  95]
 [ 86  21  38  20]
 [ 87  66  47  24]
 [ 19  12  13  46]
 [ 32  57  87  88]
 [ 59   2  10 100]
 [ 17  51  40  68]
 [  3  80  27   2]
 [ 47  37  89  52]
 [ 65   7  96  96]
 [ 79  34  97  53]
 [ 93  59  16  13]
 [ 34  16  23  30]
 [ 76  82   6  68]
 [ 58  48  17  31]
 [  3  73   2  57]
 [ 40   0 

In [64]:
import numpy as np
#operacje matematyczne i logiczne
a = np.random.uniform(0, 10, (3,3))
b = np.random.uniform(0, 10, (3,3))
print(a)
print(b)
print('dodawanie', a+b)
print('mnożenie', a*b)
print('dzielenie', a/b)
print('potęgowanie', a**b)
print(a > 4)
print(a.all() >= 1 and a.all() <= 4)
print(np.trace(b))

[[6.35788451 7.24760184 5.0387683 ]
 [7.50778893 8.26651387 2.88874697]
 [9.27147382 5.96395693 2.50990433]]
[[9.87619901 0.67135585 9.35028777]
 [6.1750483  4.65229397 8.54717939]
 [9.773989   6.50354229 6.35054236]]
dodawanie [[16.23408352  7.91895769 14.38905607]
 [13.68283723 12.91880784 11.43592636]
 [19.04546282 12.46749923  8.8604467 ]]
mnożenie [[62.79173271  4.86571989 47.11393358]
 [46.3609593  38.45825263 24.69063858]
 [90.61928314 38.78684616 15.9392538 ]]
dzielenie [[ 0.64375824 10.79546985  0.53888911]
 [ 1.21582675  1.77686834  0.33797664]
 [ 0.94858648  0.91703208  0.39522677]]
potęgowanie [[8.58371817e+07 3.78004085e+00 3.68922495e+06]
 [2.54876167e+05 1.85205323e+04 8.66496415e+03]
 [2.83727545e+09 1.10591414e+05 3.45175354e+02]]
[[ True  True  True]
 [ True  True False]
 [ True  True False]]
True
20.87903534663872


In [67]:
import numpy as np
#dane statystyczzne
b = np.random.uniform(0, 10, (3,3))
print(b)
print(np.min(b))
print(np.max(b))
print(np.std(b))
print(np.mean(b, axis=1))

[[9.54926166 6.43723844 3.59876423]
 [0.0278494  6.45355956 4.88085027]
 [2.34351424 3.18802426 2.28778039]]
0.027849396741145283
9.549261656794837
2.686459921562885
[6.52842144 3.78741974 2.60643963]


In [11]:
import numpy as np
#rzutowanie wymiarów
a = np.random.random(50)
print(a)
print(a.reshape((10, 5)))
a = np.resize(a, (10, 5))
print(a)
print(a.ravel())
b = np.random.random(5)
print(b)
c = np.random.random(4)
print(c)
# print(b+c)
b = b[:, np.newaxis]
print(b)
print(b+c)

[0.5619365  0.11158288 0.97917963 0.74423961 0.78397525 0.91125917
 0.02488619 0.6232902  0.59167351 0.48930561 0.79260568 0.26627949
 0.57000762 0.30902354 0.61669544 0.51386026 0.99306722 0.78864612
 0.09918055 0.68973559 0.88129472 0.47568371 0.92368321 0.82782085
 0.60361793 0.50732443 0.68081951 0.66453427 0.15571055 0.61770087
 0.31248525 0.10174177 0.70087487 0.03017368 0.91404196 0.5191029
 0.89414423 0.71515223 0.96422994 0.26213982 0.94082484 0.49907156
 0.97627008 0.97151949 0.81732162 0.3682621  0.17655257 0.63473232
 0.88404429 0.55363294]
[[0.5619365  0.11158288 0.97917963 0.74423961 0.78397525]
 [0.91125917 0.02488619 0.6232902  0.59167351 0.48930561]
 [0.79260568 0.26627949 0.57000762 0.30902354 0.61669544]
 [0.51386026 0.99306722 0.78864612 0.09918055 0.68973559]
 [0.88129472 0.47568371 0.92368321 0.82782085 0.60361793]
 [0.50732443 0.68081951 0.66453427 0.15571055 0.61770087]
 [0.31248525 0.10174177 0.70087487 0.03017368 0.91404196]
 [0.5191029  0.89414423 0.71515223 

In [22]:
import numpy as np
#sortowanie danych
a = np.random.randn(5, 5)
print(a)
a = np.sort(a, axis=0) # rows
print(a)
a = np.sort(a, axis=1)[:, ::-1] # cols
print(a)

b = np.array([(1, 'MZ', 'mazowieckie'), (2, 'ZP', 'zachodniopomorskie'), (3, 'ML', 'małopolskie')])
print(b.ndim)
print(b.size)

[[-0.27169556  0.92174544  0.49925496  1.50674715  0.98203407]
 [ 0.49713968  0.86711204 -1.26559952  0.16130291  0.22743867]
 [ 0.11664277  0.22318903 -0.72226019 -1.67476482  0.1978183 ]
 [ 1.63101474  0.13852361 -1.55438896 -0.66573888  1.16686767]
 [ 2.09040446 -0.89559578 -0.87309116  0.6037538   0.18498821]]
[[-0.27169556 -0.89559578 -1.55438896 -1.67476482  0.18498821]
 [ 0.11664277  0.13852361 -1.26559952 -0.66573888  0.1978183 ]
 [ 0.49713968  0.22318903 -0.87309116  0.16130291  0.22743867]
 [ 1.63101474  0.86711204 -0.72226019  0.6037538   0.98203407]
 [ 2.09040446  0.92174544  0.49925496  1.50674715  1.16686767]]
[[ 0.18498821 -0.27169556 -0.89559578 -1.55438896 -1.67476482]
 [ 0.1978183   0.13852361  0.11664277 -0.66573888 -1.26559952]
 [ 0.49713968  0.22743867  0.22318903  0.16130291 -0.87309116]
 [ 1.63101474  0.98203407  0.86711204  0.6037538  -0.72226019]
 [ 2.09040446  1.50674715  1.16686767  0.92174544  0.49925496]]
2
9


In [26]:
import numpy as np
#zadanie 1
a = np.random.randint(-1000, 1000, (10, 5))
print(np.trace(a))
print(np.diag(a))

-442
[ -12 -935   97 -388  796]


In [28]:
import numpy as np
#zadanie 2
a = np.random.normal(0, 1, 5)
b = np.random.normal(0, 1, 5)
print(a * b)

[1.84774286 0.14744746 0.18425603 0.82360603 1.11686188]


In [30]:
import numpy as np
#zadanie 3
a = np.random.randint(1, 101, 5)
b = np.random.randint(1, 101, 5)
print(a)
print(b)
a = a[:, np.newaxis]
print(a)
print(a+b)

[100  69  72  89   1]
[85 18 65  6 55]
[[100]
 [ 69]
 [ 72]
 [ 89]
 [  1]]
[[185 118 165 106 155]
 [154  87 134  75 124]
 [157  90 137  78 127]
 [174 107 154  95 144]
 [ 86  19  66   7  56]]


In [37]:
import numpy as np
#zadanie 4
a = np.random.randint(1, 101, (4, 5))
b = np.random.randint(1, 101, (5, 4))
a = a.T # a.reshape(5, 4)
print(a+b)
#zadanie 5 
print(a[:, 2] * b[:, 3])

[[ 75 112  98  72]
 [ 93 176  81  69]
 [ 56  82  97  31]
 [124 133 142 129]
 [ 84 163 137  21]]
[2414 3975  584 5917  416]


In [41]:
import numpy as np
#zadanie 6
a = np.random.normal(size=(3, 3))
b = np.random.uniform(size=(3, 3))
print(np.mean(a), np.std(a), np.var(a))
print(np.mean(b), np.std(b), np.var(b))


[[-0.88929287  0.39463993 -2.22226541]
 [ 0.23534757  1.207897   -1.10740007]
 [ 0.88672059  0.11340138  1.43305666]]
[[0.92296892 0.49041018 0.28200418]
 [0.829527   0.16428427 0.75559965]
 [0.43461277 0.95031597 0.2589976 ]]
0.00578942065383946 1.1293197366688215 1.275363067629736
0.565413393028688 0.2867001979137078 0.08219700348375925


In [40]:
import numpy as np
#zadanie 7
a = np.random.randint(1, 10, size=(3, 3))
b = np.random.randint(1, 10, size=(3, 3))
print(a)
print(b)
print(a*b) # mnozenie element po elemencie, na przyklad gdy chcemy pomnozyc kazdy element prez pewne skalary
print(np.dot(a, b)) # standardowe mnozenie macierzowe

[[5 2 3]
 [1 8 3]
 [3 5 9]]
[[1 9 2]
 [3 1 1]
 [7 8 7]]
[[ 5 18  6]
 [ 3  8  3]
 [21 40 63]]
[[ 32  71  33]
 [ 46  41  31]
 [ 81 104  74]]


In [1]:
import numpy as np
#zadanie 8
a = np.random.randint(1, 51, (6, 6))
print(a)
b = np.lib.stride_tricks.as_strided(a, shape=(3, 5), strides=a.strides)
print(b)
print(a.strides)

[[36 21 12  8 33 12]
 [30 33 30 18 24 18]
 [43 29 35 35 32 25]
 [14  5  1 50 39 43]
 [12 18 48 24  9 27]
 [27 36 22 18 24 35]]
[[36 21 12  8 33]
 [30 33 30 18 24]
 [43 29 35 35 32]]
(48, 8)


In [8]:
import numpy as np
#zadanie 9
a = np.arange(5)
b = np.arange(5)
print(np.vstack((a, b))) # laczanie pionowo, czyli dodanie nowych wierszy
                         # jest przydatne, na przyklad, gdy dodawane sa nowe dane z tymi samymi atrybutami
print(np.hstack((a, b))) # laczanie poziomowo, czyli dodanie nowych kolumn
                         # jest przydatne, na przykald, gdy dodawane sa nowe atrybuty dla calego zestawu danych

[[0 1 2 3 4]
 [0 1 2 3 4]]
[0 1 2 3 4 0 1 2 3 4]


In [1]:
import numpy as np
# zadanie 10
a = np.arange(24).reshape(4, 6)
print(a)
print(np.max(np.lib.stride_tricks.as_strided(a, shape=(2, 3), strides=a.strides)))
print(np.max(np.lib.stride_tricks.as_strided(a[:, 3:], shape=(2, 3), strides=a.strides)))
print(np.max(np.lib.stride_tricks.as_strided(a[2:, :], shape=(2, 3), strides=a.strides)))
print(np.max(np.lib.stride_tricks.as_strided(a[2:, 3:], shape=(2, 3), strides=a.strides)))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
8
11
20
23
